### PR TITLE
Address compiler warnings

### PR DESCRIPTION
**Pull request by ligustah**

### CODE REVIEW

**Comment by ligustah** [comment]
* **#88** <a href="https://app.graphite.dev/github/pr/ourzora/mintpool/88?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ligustah and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by erikreppel** [comment]
@ligustah I think this is missing a trait import, compile fails

**Comment by ligustah** [comment]
> @ligustah I think this is missing a trait import, compile fails

Oh, lazy compiler got me there. Will fix tomorrow

**Comment by ligustah** [comment]
@erikreppel should be fixed

**Review by erikreppel — APPROVED** [review]

**Pull request merged**
